### ISSUE TITLE
api url syntax needs change

### ISSUE THREAD

**Issue by itsmehecker** [zisra/movie-cli#17]
err message:
> movie-cli@1.0.0 start
> tsx ./src/index.ts

(node:2986) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("file%3A///Users/itsmhecker/movie-cli/node_modules/tsx/dist/loader.js", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Enter a movie or show name … Simpsons
 (404 Not Found (https://apis.justwatch.com/content/titles/en_US/popular?body=%7B%22content_types%22:%5B%22show%22,%22movie%22%5D,%22page%22:1,%22query%22:%22Simpsons%22,%22page_size%22:40%7D))

I checked with the api url I think they changed how the url was

**Comment by zisra** [comment]
Basically #12
